apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: {{ .Values.phpmyadmin.replicaCount }}
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image.name }}:{{ .Values.phpmyadmin.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: {{ .Release.Name }}-mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-secret
                  key: USERNAME
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-secret
                  key: PASSWORD
